language: node_js
node_js:
  - 10
git:
  depth: 1
branches:
  only:
    - master
jobs:
  include:
    - stage: client build
      before_script:
        - cd client
        - npm install
      script:
        - npm run build
        - cd ..

    - stage: server build
      before_script:
        - cd server
        - npm install
      script:
        - npm run build
        - cd ..
